### ISSUE TITLE
Submit to extensions dir

### ISSUE THREAD

**Issue by eileenmcnaughton** [progressivetech/net.ourpowerbase.exportpermission#1]
Hi @jmcclelland if you put this up for the extensions dir I will review it

**Comment by jmcclelland** [comment]
Done: https://civicrm.org/extensions/export-permission

Thanks Eileen.

**Comment by eileenmcnaughton** [comment]
@jmcclelland I think you were supposed to open a JIRA - I've done so & approved this

https://issues.civicrm.org/jira/browse/EXT-79
