### ISSUE TITLE
How about reports

### ISSUE THREAD

**Issue by thomas-SGB** [progressivetech/net.ourpowerbase.exportpermission#3]
We love the ability to restrict the access to export in search results. 

We would really love to have the same ability in report results. How can we make this happen? Is there a chance to block it from actions menu in report results?

**Comment by jmcclelland** [comment]
That sounds like a great idea. I haven't checked the code but I imagine it would be possible. I would be open to a pull request, but don't have the time to implement it myself.

**Comment by andyburnsco** [comment]
I would be interested in funding this. Please contact me at https://chat.civicrm.org/civicrm/messages/@andyburns

**Comment by mattwire** [comment]
Fixed in 1.2

**Comment by jmcclelland** [comment]
Thanks for the fix on this ticket. The new release is tagged and should be available tomorrow
