### ISSUE TITLE
Activities search fails for users without permission of access_print_menu 

### ISSUE THREAD

**Issue by andyburnsco** [progressivetech/net.ourpowerbase.exportpermission#6]
If a user does not have "access_print_menu" they can not the open activities or mailings tab in adv search (network error). They also get WSOD going to search > find activities. So activities is a problem, maybe other areas I am unaware of.

![export-perm-ext](https://user-images.githubusercontent.com/18341942/126843356-e1bd9d31-cc79-4451-81cd-9e7ca04f0532.png)

This is a breaking change on version 1.2 from this PR: https://github.com/progressivetech/net.ourpowerbase.exportpermission/pull/4. Not sure what the connection is. @mattwire 

General issue on why this may occur: https://civicrm.stackexchange.com/questions/31318/network-error-unable-to-reach-the-server-recording-contact-activities

**Comment by mattwire** [comment]
@andyburnsco Please can you test https://github.com/civicrm/civicrm-core/pull/20940? - You can probably just apply this bit: https://github.com/civicrm/civicrm-core/pull/20940/commits/f2baa7e02ed337adcc723dc8f1ae27151e337759

**Comment by andyburnsco** [comment]
@mattwire I only applied https://github.com/civicrm/civicrm-core/commit/f2baa7e02ed337adcc723dc8f1ae27151e337759 patch and it does allow activities and mailings tab in advanced search to work. However, Search > Find Activities results in WSOD still.

It is only when I give the _access_print_menu that Find Activities search screen "works" again.

**Comment by mattwire** [comment]
@andyburnsco Ah, problem seems more widespread - try https://github.com/civicrm/civicrm-core/pull/20950 for a more generic fix (you can remove the previous patch).

**Comment by andyburnsco** [comment]
I've applied https://github.com/civicrm/civicrm-core/pull/20950/commits/222ce04757bc5f938007928765f73f60c738ce06 and rolled back this patch https://github.com/civicrm/civicrm-core/commit/f2baa7e02ed337adcc723dc8f1ae27151e337759. 

Find Activities works now. Looks good.
